---
- name: Install and configure apache
  hosts: manage1
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: copy the index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: start the http service
      service:
        name: httpd
        state: started
        enabled: true

